import { useEffect, useState } from "react";
import { api } from "../utils/api";
import { useNavigate, useSearchParams } from "react-router-dom";
import "./Products.css";
import { useDebouncedValue } from "../utils/useDebouncedValue";

const blank = { name:"", sku:"", category:"", description:"", costPrice:"", sellingPrice:"", quantity:"", minimumStock:"" };
const categories = ["Electronics","Clothing","Grocery","Furniture","Stationery","Hardware","Other"];
const Field = ({label, wide, children}) => <div className={`form-field${wide ? " full-width" : ""}`}><label>{label}</label>{children}</div>;

export default function Products() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [products,setProducts] = useState([]), [loading,setLoading] = useState(true), [error,setError] = useState("");
  const [showForm,setShowForm] = useState(false), [editing,setEditing] = useState(null), [saving,setSaving] = useState(false), [formError,setFormError] = useState(""), [form,setForm] = useState(blank);
  const [search,setSearch] = useState(() => searchParams.get("search") || ""), [category,setCategory] = useState(""), [stock,setStock] = useState("");
  const debouncedSearch = useDebouncedValue(search, 300);
  const getProducts = async () => { try { setLoading(true); setError(""); const response = await fetch(api("/api/products"),{credentials:"include"}); const data = await response.json(); if(!response.ok) throw new Error(data.message || "Failed to get products"); setProducts(data.products || []); } catch(e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => {
    const requestId = window.setTimeout(() => { getProducts(); }, 0);
    return () => window.clearTimeout(requestId);
  }, []);
  const close = () => { setShowForm(false); setEditing(null); setForm(blank); setFormError(""); };
  const change = ({target:{name,value}}) => setForm((prev) => ({...prev,[name]:value}));
  const openEdit = (product) => { setEditing(product); setForm({name:product.name,sku:product.sku,category:product.category,description:product.description || "",costPrice:product.costPrice,sellingPrice:product.sellingPrice,quantity:product.quantity,minimumStock:product.minimumStock}); setFormError(""); setShowForm(true); };
  async function save(event) { event.preventDefault(); setFormError(""); const needed = ["name","sku","category","costPrice","sellingPrice","quantity","minimumStock"]; if(needed.some((key) => !String(form[key]).trim())) return setFormError("Please fill in all required fields."); if(["costPrice","sellingPrice","quantity","minimumStock"].some((key) => Number(form[key]) < 0)) return setFormError("Prices and stock values cannot be negative."); try { setSaving(true); const response = await fetch(editing ? api(`/api/products/${editing._id}`) : api("/api/products"),{method:editing ? "PUT" : "POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,name:form.name.trim(),sku:form.sku.trim(),description:form.description.trim(),costPrice:Number(form.costPrice),sellingPrice:Number(form.sellingPrice),quantity:Number(form.quantity),minimumStock:Number(form.minimumStock)})}); const data = await response.json(); if(!response.ok) throw new Error(data.message || "Failed to save product"); close(); await getProducts(); } catch(e) { setFormError(e.message); } finally { setSaving(false); } }
  async function remove(id) { if(!window.confirm("Are you sure you want to delete this product?")) return; try { const response = await fetch(api(`/api/products/${id}`),{method:"DELETE",credentials:"include"}); const data = await response.json(); if(!response.ok) throw new Error(data.message || "Failed to delete product"); await getProducts(); } catch(e) { setError(e.message); } }
  const filtered = products.filter((p) => { const q=Number(p.quantity || 0), min=Number(p.minimumStock || 0), text=[p.name,p.sku].some((v) => (v || "").toLowerCase().includes(debouncedSearch.toLowerCase())); const inventory=stock === "in" ? q > min : stock === "low" ? q > 0 && q <= min : stock === "out" ? q===0 : true; return text && (!category || p.category===category) && inventory; });
  if(loading) return <main className="products-page page-loading"><div className="loading-spinner"/>Loading products...</main>;
  return <main className="products-page"><header className="products-header"><div><button className="dashboard-back-button" onClick={() => navigate("/Admin")}>Back to dashboard</button><h1 className="products-title">Products</h1><p className="products-subtitle">Manage your product catalog and stock levels</p></div>{!showForm && <button className="primary-button" onClick={() => {setForm(blank);setEditing(null);setShowForm(true);}}>+ Add product</button>}</header>{error && <div className="error-box">{error}</div>}
    {showForm && <section className="product-form-card"><div className="product-form-header"><div><h2 className="product-form-title">{editing ? "Edit product" : "Add product"}</h2><p>Enter the details needed to track this item.</p></div><button className="close-button" onClick={close} aria-label="Close">&times;</button></div>{formError && <div className="error-box">{formError}</div>}<form onSubmit={save}><div className="product-form-grid"><Field label="Product name *"><input name="name" value={form.name} onChange={change} placeholder="e.g. Wireless mouse"/></Field><Field label="SKU *"><input name="sku" value={form.sku} onChange={change} placeholder="e.g. WM-001"/></Field><Field label="Category *"><select name="category" value={form.category} onChange={change}><option value="">Select a category</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Description" wide><textarea name="description" value={form.description} onChange={change} rows="3" placeholder="Optional product description"/></Field><Field label="Cost price *"><input type="number" min="0" step="0.01" name="costPrice" value={form.costPrice} onChange={change}/></Field><Field label="Selling price *"><input type="number" min="0" step="0.01" name="sellingPrice" value={form.sellingPrice} onChange={change}/></Field><Field label="Opening quantity *"><input type="number" min="0" name="quantity" value={form.quantity} onChange={change}/></Field><Field label="Low-stock threshold *"><input type="number" min="0" name="minimumStock" value={form.minimumStock} onChange={change}/></Field></div><div className="form-actions"><button type="button" className="secondary-button" onClick={close} disabled={saving}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : editing ? "Update product" : "Save product"}</button></div></form></section>}
    {!showForm && <><section className="products-toolbar"><input className="search-input" placeholder="Search by product name or SKU" value={search} onChange={(e)=>setSearch(e.target.value)}/><select className="category-filter" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map((item)=><option key={item}>{item}</option>)}</select><select className="category-filter" value={stock} onChange={(e)=>setStock(e.target.value)}><option value="">All stock levels</option><option value="in">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select><button className="clear-filters-button" onClick={()=>{setSearch("");setCategory("");setStock("");}}>Clear filters</button></section><section className="products-table-card"><div className="table-card-header"><div><h2>Product catalog</h2><p>{filtered.length} of {products.length} products shown</p></div></div>{filtered.length===0?<div className="empty-state"><h3>No matching products</h3><p>Try changing your search or filters.</p></div>:<div className="products-table-wrapper"><table className="products-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Cost</th><th>Price</th><th>On hand</th><th>Min. stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map((p)=>{const q=Number(p.quantity||0),min=Number(p.minimumStock||0),out=q===0,low=q>0&&q<=min;return <tr key={p._id}><td><div className="product-cell"><span>{p.name?.slice(0,1).toUpperCase()}</span><div><strong>{p.name}</strong><small>{p.description||"No description"}</small></div></div></td><td>{p.sku}</td><td>{p.category}</td><td>{Number(p.costPrice).toFixed(2)}</td><td>{Number(p.sellingPrice).toFixed(2)}</td><td>{q}</td><td>{min}</td><td><span className={`stock-status ${out?"out-of-stock":low?"low-stock":"in-stock"}`}>{out?"Out of stock":low?"Low stock":"In stock"}</span></td><td><div className="table-actions"><button className="edit-button" onClick={()=>openEdit(p)}>Edit</button><button className="delete-button" onClick={()=>remove(p._id)}>Delete</button></div></td></tr>})}</tbody></table></div>}</section></>}
  </main>;
}
